# $FreeBSD: src/sys/modules/bge/Makefile,v 1.4 2005/09/27 18:10:33 mlaier Exp $

.PATH: ${.CURDIR}/../../dev/bge

KMOD=	if_bge
SRCS=	opt_bge.h if_bge.c miibus_if.h miidevs.h device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
