# $FreeBSD: src/usr.sbin/setfmac/Makefile,v 1.3 2002/12/02 03:22:57 rwatson Exp $

PROG=   setfmac
MAN=	setfmac.8
SRCS=   setfmac.c
.PATH:	${.CURDIR}/../../usr.sbin/setfmac

LINKS+=	${BINDIR}/setfmac ${BINDIR}/setfsmac

MLINKS+=	setfmac.8 setfsmac.8

WARNS?=	2

.include <bsd.prog.mk>
