# $Id$
# $FreeBSD: src/sys/modules/netgraph/bluetooth/Makefile,v 1.3 2006/02/18 23:49:27 yar Exp $

SUBDIR=	\
	bluetooth \
	hci	\
	l2cap	\
	socket	\
	bt3c	\
	h4	\
	ubt	\
	ubtbcmfw

.include <bsd.subdir.mk>
