#!/bin/sh
#
# Add additional swap files
#
# $FreeBSD: src/etc/rc.d/addswap,v 1.6 2006/01/17 19:29:31 philip Exp $
#

# PROVIDE: addswap
# REQUIRE: mountcritlocal
# BEFORE: sysctl
# KEYWORD: nojail

. /etc/rc.subr

name="addswap"
start_cmd="addswap_start"
stop_cmd=":"

addswap_start()
{
	case ${swapfile} in
	[Nn][Oo] | '')
		;;
	*)
		if [ -w "${swapfile}" ]; then
			echo "Adding ${swapfile} as additional swap"
			mdev=`mdconfig -a -t vnode -f ${swapfile}` && swapon /dev/${mdev}
		fi
		;;
	esac
}

load_rc_config $name
run_rc_command "$1"
