#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/devd,v 1.8 2005/10/28 16:55:38 yar Exp $
#

# PROVIDE: devd
# REQUIRE: NETWORKING
# BEFORE: mountcritremote
# KEYWORD: nojail

. /etc/rc.subr

name="devd"
rcvar=`set_rcvar`
command="/sbin/${name}"

load_rc_config $name
run_rc_command "$1"

# If devd is disabled, turn it off in the kernel to avoid memory leaks.
if ! checkyesno ${rcvar}; then
    sysctl hw.bus.devctl_disable=1
fi
