#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/powerd,v 1.3 2005/10/28 16:55:38 yar Exp $
#

# PROVIDE: powerd
# REQUIRE: DAEMON
# BEFORE: LOGIN
# KEYWORD: nojail

. /etc/rc.subr

name="powerd"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
