# $FreeBSD: src/sys/modules/geom/Makefile,v 1.15 2005/07/27 21:47:55 pjd Exp $

SUBDIR=	geom_apple \
	geom_bde \
	geom_bsd \
	geom_ccd \
	geom_concat \
	geom_eli \
	geom_fox \
	geom_gate \
	geom_gpt \
	geom_label \
	geom_mbr \
	geom_mirror \
	geom_nop \
	geom_pc98 \
	geom_raid3 \
	geom_shsec \
	geom_stripe \
	geom_sunlabel \
	geom_uzip \
	geom_vinum \
	geom_vol_ffs \
	geom_zero

.include <bsd.subdir.mk>
