# $Id$
# $FreeBSD: src/usr.sbin/bluetooth/Makefile,v 1.6 2004/01/25 21:33:58 emax Exp $

SUBDIR= \
	bcmfw \
	bt3cfw \
	hccontrol \
	hcsecd \
	hcseriald \
	l2control \
	l2ping \
	rfcomm_pppd \
	sdpcontrol \
	sdpd

.include <bsd.subdir.mk>

