#	from: @(#)Makefile	5.2 (Berkeley) 5/11/90
# $FreeBSD: src/usr.bin/rpcinfo/Makefile,v 1.7 2006/03/10 07:58:02 deischen Exp $

PROG=	rpcinfo
SRCS=	rpcinfo.c
MAN=	rpcinfo.8

CFLAGS+=	-DPORTMAP -DINET6

.include <bsd.prog.mk>
