#$FreeBSD: src/sys/modules/myri10ge/myri10ge/Makefile,v 1.1 2006/02/19 22:39:19 gallatin Exp $

.PATH: ${.CURDIR}/../../../dev/myri10ge

KMOD=	if_myri10ge
SRCS=	if_myri10ge.c device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
