# $FreeBSD: src/lib/libgpib/Makefile,v 1.3 2006/03/16 15:18:15 ru Exp $

LIB =		gpib
SHLIBDIR ?=	/lib
SHLIB_MAJOR =	1
SRCS =		ibfoo.c
INCS =		gpib.h
INCSDIR =	${INCLUDEDIR}/gpib
WARNS?=		6

.include <bsd.lib.mk>
