# $FreeBSD: src/usr.sbin/pcvt/Makefile,v 1.8 2005/07/15 07:44:57 phk Exp $

SUBDIR= 	keycap cursor fontedit fonts kcon loadfont scon \
		userkeys ispcvt
SUBDIR+=	vgaio kbdio
SUBDIR+=	demo
SUBDIR+=	Misc

.include <bsd.subdir.mk>
