# $FreeBSD: src/share/doc/papers/Makefile,v 1.16 2005/08/01 12:14:52 phk Exp $

SUBDIR=	beyond4.3 \
	bufbio \
	contents \
	devfs \
	diskperf \
	hwpmc \
	fsinterface \
	jail \
	kernmalloc \
	kerntune \
	malloc \
	newvm \
	relengr \
	sysperf \
	timecounter

.include <bsd.subdir.mk>
